wc_music_corp:
  format_pdf_config:
    ignore_tables: 1
    tables:
      foreign_tax_summary:
        enhance_table_data:
        - add_page_numbers      
        normalize_column_names: true
        drop_last_rows: 1
        replace_values:
          replace_config:
            ',': ''
        col_types:
          type_mappings:
            gross_payable: float
            tax_rate: float
            withholding_tax: float
            net_payable: float
        fillna:
          how:
            territory_name: ffill
            tax_rate: ffill
        query:
          query_string:
            '~income_type_group.str.contains(r"All\s\(\d{1}\sTypes\)")'
      income_type_group_summary:
        enhance_table_data:
        - add_page_numbers      
        normalize_column_names: true
        replace_values:
          replace_config:     
            ',': ''
        drop_last_rows: 1
        col_types:
          type_mappings:
            gross_payable: float
            withholding_tax: float
            net_payable: float
      scope_summary:
        enhance_table_data:
        - add_page_numbers
        normalize_column_names: true
        replace_values:
          replace_config:     
            ',': ''
        drop_last_rows: 1
        col_types:
          type_mappings:
            gross_payable: float
            withholding_tax: float
            net_payable: float                     
      music_royalties:
        enhance_table_data:
        - scope
        - track_titles
        - add_page_numbers
        normalize_column_names: true
        query:
          query_string:
            '~units.isna()'       
        replace_values:
          replace_config:
            '@': ''     
            ',': ''
        fillna:
          how:
            scope: ffill
        col_types:
          type_mappings:
            statement_id: int
            units: int
            amount_received: float
            royalty_rate: float
            amount_paid: float
  validate_pdf_config:
    report_output_name: test_report.pdf
    style: 
    tables:
      foreign_tax_summary:
        validate_amount_due: net_payable
      income_type_group_summary:
        validate_amount_due: net_payable
      scope_summary:
        validate_amount_due: net_payable
      music_royalties:
        validate_scope_sum: true
        validate_track_sum: true
